# We need super user permissions to use Docker
sudo: required
services:
  - docker

before_install:
  - docker build -t kinano/docker-react -f Dockerfile.dev .

script:
  # Tell npm run test to exit once it is done
  - docker run kinano/docker-react npm run test -- --coverage

